trigger:
  - master

stages:
  - stage: Build
    displayName: 'Build .NET Application'
    jobs:
      - job: Build
        displayName: 'Build'
        pool:
          vmImage: 'windows-latest'

        variables:
          RestoreBuildProjects: '**/*.csproj'
          targetRuntime: 'win-x64'

        steps:
          - task: UseDotNet@2
            displayName: 'Install .NET Core SDK.'
            inputs:
              version: 8.0.204
              performMultiLevelLookup: true
              includePreviewVersions: true  # Required for preview versions

          - task: UseDotNet@2
            displayName: Restore
            inputs:
              command: 'restore'
              projects: '$(RestoreBuildProjects)'
              feedsToUse: 'select'

          - task: UseDotNet@2
            displayName: Build
            inputs:
              command: 'build'
              feedsToUse: config
              nugetConfigPath: NuGet.config
              projects: '$(RestoreBuildProjects)'
              arguments: '--configuration $(BuildConfiguration)'

          - task: UseDotNet@2
            displayName: 'Publish'
            inputs:
              command: 'publish'
              publishWebProjects: false
              projects: '$(RestoreBuildProjects)'
              arguments: '--configuration $(BuildConfiguration) --runtime $(targetRuntime) --output $(Build.ArtifactStagingDirectory)'
              zipAfterPublish: true

          
          - task: DownloadBuildArtifacts@1
            inputs:
              buildType: 'current'
              downloadType: 'single'
              artifactName: '/*.zip'
              downloadPath: '$(Build.ArtifactStagingDirectory)'