trigger:
  - master

stages:
  - stage: Build
    displayName: 'Build .NET Application'
    jobs:
      - job: Build
        displayName: 'Build'
        pool:
          vmImage: 'windows-latest'

        variables:
          RestoreBuildProjects: '**/*.csproj'
          targetRuntime: 'win-x64'
          ArtifactFolder: '$(System.DefaultWorkingDirectory)/artifacts'

        steps:
          - task: UseDotNet@2
            displayName: 'Install .NET Core SDK.'
            inputs:
              version: 8.0.204
              performMultiLevelLookup: true
              includePreviewVersions: true  # Required for preview versions

          - task: UseDotNet@2
            displayName: 'Restore'
            inputs:
              command: 'restore'
              projects: '$(RestoreBuildProjects)'
              feedsToUse: 'select'

          - task: UseDotNet@2
            displayName: 'Build'
            inputs:
              command: 'build'
              feedsToUse: 'config'
              nugetConfigPath: 'NuGet.config'
              projects: '$(RestoreBuildProjects)'
              arguments: '--configuration $(BuildConfiguration) --output $(System.DefaultWorkingDirectory)'

        

          - powershell: |
              New-Item -ItemType Directory -Path $(ArtifactFolder) -Force
              Move-Item -Path "$(Build.ArtifactStagingDirectory)\*" -Destination $(ArtifactFolder)
            displayName: 'Move artifacts to folder'

          - task: PublishBuildArtifacts@1
            displayName: 'Publish Artifact'
            inputs:
              PathtoPublish: '$(ArtifactFolder)'
